### ISSUE TITLE
Removal of non-active Algiers chapter for the purpose of recreation

### ISSUE THREAD

**Issue by shakesBeardZ** [nodeschool/organizers#524]
Hi, I'm a Nodejs developer who wants to organise Nodeschool events for the purpose of sharing my experience in the NodeJS world and teaching people Javascript in Algiers, Algeria.
Anyway, In the last few months tried to contact the Algiers node chapter organizers which's now totally non-active, but I didn't get any response, they organised 2 events at the beginning but they stopped , I think it's 2 years now and they didn't do anything and I've waited a lot.
Now I think It's time for their removal and recreation and if they want to join they are more than welcome to help us grow Nodejs community in Algeria.
By the way I'm orginising a workshop + conference on NodeJS the Next month in my University with more than 300 attendees so it's gonna the right time for this move.

**Comment by riyadhalnur** [comment]
I think the best course of action now is for you to take the existing chapter. I'll add you in and you can take it from there. Existing organisers will be a part of the team. Their removal depends solely on their consent.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team algiers

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 422
    at Request._callback (/home/nowuser/src/server.js:344:17)
    at Request.self.callback (/home/nowuser/src/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user algiers shakesBeardZ

**Comment by riyadhalnur** [comment]
I have invited @shakesBeardZ to the `algiers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user shakesBeardZ

**Comment by riyadhalnur** [comment]
I have added @shakesBeardZ to the `chapter-organizers` team.
